### PR TITLE
Lock the updater/proxy images to latest sha256

### PR DESCRIPTION
**Pull request by feelepxyz**
Pin the updater and proxy images to the latest sha256 release. We still
want some automation to update this but opening this PR to do the
pinning as the automation approach feel down a deep rabbit hole.

Reworking this PR: https://github.com/dependabot/updater-action/pull/71/
Working towards: github/dependabot-updates#2102

## TODO

- [ ] Pin updater to sha: `docker.pkg.github.com/dependabot/dependabot-updater@sha256:58e0fb2e0373294b05ad5e8af7d190d47a1bb3e098426c3840a31db0b0b0a931`
- [ ] Pin proxy to sha: `docker.pkg.github.com/github/dependabot-update-job-proxy@sha256:835ce18d93a9ba7336ed815cec7d43b78649cd1ce63b4559fb00f0726658a8df`
- [ ] Figure out why github packages is returning a 500 when requesting the manifests: https://github.com/dependabot/updater-action/runs/5023691247?check_suite_focus=true

### CODE REVIEW

**Comment by feelepxyz** [comment]
@landongrindheim I opened this PR in an attempt to just pin the images to the sha's but ran into this test failure: https://github.com/dependabot/updater-action/runs/5023691247?check_suite_focus=true

```
(HTTP code 500) server error - Get "[https://docker.pkg.github.com/v2/github/dependabot-update-job-proxy/manifests/sha256:835ce18d93a9ba7336ed815cec7d43b78649cd1ce63b4559fb00f0726658a8df](https://docker.pkg.github.com/v2/github/dependabot-update-job-proxy/manifests/sha256:835ce18d93a9ba7336ed815cec7d43b78649cd1ce63b4559fb00f0726658a8df)": no basic auth credentials
```

Not sure what's going on there, I think the sha syntax is correct. Are these images not public?

I think once that's figured out this could go in, then I started this follow up https://github.com/dependabot/updater-action/pull/73

**Comment by jurre** [comment]
> Are these images not public?

The settings page says they are

**Comment by brrygrdn** [comment]
Ah, the images _are_ public, but you still need a token to pull public images, this has caught me out before. I think that build may not have the login step yet.

**Comment by brrygrdn** [comment]
Closing this out as #92 pulls in the final relevant changes.

**Pull request closed without merging**
